# These are supported funding model platforms
# Hola! Si querés colaborar en mis proyectos, acá te dejo algunos datos para que puedas hacerlo!
# Agradecido eternamente con todos los que colaboren y utilicen mi código para sus propios proyectos. Eso es una especie de longevidad más allá de la propia vida.
#
#+-------------------------------------------------------+
   custom:                                               |
   MercadoPago       : link.mercadopago.com.ar/omnisis   |
#        Alias       : omnisis.mp                        |
#        CVU         : 0000003100001482160518            |
#                                                        |
#+-------------------------------------------------------+
# Soon...

#github:
#open_collective: 
#ko_fi: 
#tidelift: 
#community_bridge: 
#liberapay:
#issuehunt: 
#lfx_crowdfunding:
#polar:
#buy_me_a_coffee: 
#thanks_dev:
